### ISSUE TITLE
Create proper README

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#1]
- Example scripts for standalone and pure-docker version
- link to {pkgcheck} and rOpenSci
- install instructions
- explain rolling release (I already removed all tags and package labels to prevent people using it wrong)

**Comment by mpadge** [comment]
Feel free to assign tasks to me, BTW! Thanks so much for all this awesome work!

**Comment by assignUser** [comment]
@mpadge  https://github.com/ropensci-review-tools/pkgcheck-action/tree/readme
