### ISSUE TITLE
Comment on PR

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#15]
@mpadge Do you think people would want the results posted to PRs from outside the repo? Probably only for checks that are not already covered by the usual rcmdcheck etc. CI if at all?

**Comment by mpadge** [comment]
I doubt there'd be much use for posting to issues from external PRs - the checks are mostly structural, rather than related to actual content of code files, and these things aren't likely to be changed with PRs. I think it's okay to just have checks posted to issues from code within the repo.

**Comment by assignUser** [comment]
I agree, in the end keeping the code of contributions up to par would be the maintainer's/pr reviewer's job.
