### ISSUE TITLE
Fix pure-docker Action

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#2]
- set exit code 1 on :heavy_multiplication_x: 
- fix visnet file path
- cleanup R scrips

**Comment by mpadge** [comment]
I had a bit of a look at that failing visnet path, but couldn't directly see why that had gone wrong - a fix there would be great, and critical if we're going to implement #4.

**Comment by assignUser** [comment]
It was located in the container tmp which of course is gone once the step finishes, I know copy everything to the wd and that should solve that.
