### ISSUE TITLE
Error on  :heavy_multiplication_x: in summary only

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#20]
![image](https://user-images.githubusercontent.com/16141871/151767250-bab1c668-fc90-4de2-a7db-6d3ee0303d24.png)
I will refine the error check to only `exit 1` on :heavy_multiplication_x:  in the summary.

_Originally posted by @assignUser in https://github.com/ropensci-review-tools/pkgcheck-action/issues/3#issuecomment-1025525358_

**Comment by mpadge** [comment]
Nice catch, thanks!
