### ISSUE TITLE
goodpractice has been removed from CRAN

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck-action#29]
Got removed 27 April 2022. Don't know why, but the build action now fails without it. Easy to fix here by inserting a remote install line. @assignUser do you wanna take care of that?

**Comment by mpadge** [comment]
@assignUser This commit https://github.com/ropensci-review-tools/pkgcheck/commit/87a45c8b33b1d80c689635f43976108296f3a85b updates the `pkgcheck` Docker container by installing `goodpractice` from GitHub which should propagate changes over to here once it builds.

**Comment by mpadge** [comment]
https://github.com/MangoTheCat/goodpractice/issues/154 - still not there, but on the way it seems

**Comment by assignUser** [comment]
It's back
