### ISSUE TITLE
Github grooming

### ISSUE THREAD

**Issue by assignUser** [ropensci-review-tools/pkgcheck-action#3]
- setup actions
- topics
- link to https://docs.ropensci.org/pkgcheck/
- labels
- ...

Anything else (badges?) I should add to be on brand for ros @mpadge?

**Comment by mpadge** [comment]
We only really have policies for packages themselves, with actions so new that nobody has yet thought about policies for how these repos should look. Most work from ropensci on actions is [in r-universe-org](https://github.com/r-universe-org/), where the repos have no "grooming" whatsoever. Given that, no stress here - also a very low priority task.

**Comment by assignUser** [comment]
I think the repo is in a good state atm.

**Comment by mpadge** [comment]
Nice! Note, however, that I've got an example of [a workflow that fails even though `pkgcheck` succeeds](https://github.com/hypertidy/geodist/runs/4998529787?check_suite_focus=true) - any insights there?

**Comment by assignUser** [comment]
![image](https://user-images.githubusercontent.com/16141871/151767250-bab1c668-fc90-4de2-a7db-6d3ee0303d24.png)
I will refine the error check to only `exit 1` on :heavy_multiplication_x:  in the summary.
