### ISSUE TITLE
Inconsistency of checks?

### ISSUE THREAD

**Issue by schneiderpy** [ropensci-review-tools/pkgcheck-action#32]
I am stuck with a "failed check".

Checking my package  _concstats_  with _pkgcheck_ on my local machine a came across the following issue:
In the summary popped up a failed check due to .. continuous integration, however, I have github actions for rmd check and (now) for pkgcheck
On github the bot (of pkgcheck?) the continuous integration check passed, however, it popped up a failed check for .. "Function names are duplicated in other packages"? I don't know where to look at or what function names are duplicated (I cannot check thousands of packages). This failed check does not appear on the local check (console).

**Comment by mpadge** [comment]
Oh yes, another very good question! @assignUser You may well have better suggestions than me, so please chime in. The meta-problem is #30, acknowledging that we need to restructure the documentation here. This issue indicates a clear need to explain the process for understanding failed checks. The action generates full information, but can't put it all directly on the workflow output. It nevertheless creates an "artefact" with all the information you need. To see it you need to:

1. Go to the GitHub actions page with the failed check
2. Look at the artefacts at the bottom and download the "results":

![image](https://user-images.githubusercontent.com/6697851/174254273-dd47e804-84a1-4f65-8bbc-01ba77bf6238.png)

3. Extract those results and open the HTML file locally. That has lots of fold-out sections. The one you want to know about looks like this:

![image](https://user-images.githubusercontent.com/6697851/174254505-f4f2454d-ca2a-4249-9389-1b5cd4be85d1.png)

---

Alternatively, just run the checks locally as `checks <- pkgcheck(path)`, and then run [`checks_to_markdown(checks)`](https://docs.ropensci.org/pkgcheck/reference/checks_to_markdown.html) to automatically open the full report in your browser, as  explained in [the main README](https://docs.ropensci.org/pkgcheck/#html-formatted-check-results). Continuous Integration doesn't seem to be any issue, as those GitHub actions checks don't fail there.

I'll keep this issue open until we've clearly documented this general workflow.

**Comment by assignUser** [comment]
@mpadge maybe we should switch `summary-only`'s default to `false`?

**Comment by mpadge** [comment]
> @mpadge maybe we should switch `summary-only`'s default to `false`? That way the issue should contain everything except the network...

I've tried that, but it's not really intelligible that way - it's generally hundreds of lines of guff with very ilttle visual structure. Would it be possible to put a simple note in the workflow telling people to download the artefacts for details of failures?

**Comment by assignUser** [comment]
In my testing it had the same html summary fold out thingies... so it was a bit longer but not fa full CVS-receipt... let me check

**Comment by assignUser** [comment]
@mpadge like this: https://github.com/assignUser/octolog/issues/14 this is 3 months old though so maybe something changed with the output?

**Comment by mpadge** [comment]
Oh yeah, sorry, my bad there. Yes, we definitely need `summary_only: false`. @schneiderpy you just need to follow [this example from the docs](https://github.com/ropensci-review-tools/pkgcheck-action#workflow-parameters) and you'll get the full explanations of your failing checks in the issue:

``` yaml
jobs: 
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
        with:
          summary-only: false
```

Forget what i said above about artefacts; you don't need to worry about that.

**Comment by schneiderpy** [comment]
What I have done so far:
- changed the pkgcheck.yaml as indicated above ... added summary-only:
false (worked fine .. in my opinion as a newbie, this should be the default)

However, I still encounter differences:

On my local machine summary(checks) give me the following output on my
console:

-- concstats 0.1.2
---------------------------------------------------------------------------------------------------

√ Package is already on CRAN.
√ has a 'codemeta.json' file.
√ has a 'contributing' file.
√ uses 'roxygen2'.
√ 'DESCRIPTION' has a URL field.
√ 'DESCRIPTION' has a BugReports field.
√ Package has at least one HTML vignette
√ All functions have examples.
x Package has no continuous integration checks.
√ Package coverage is 79.6%.
√ R CMD check found no errors.
√ R CMD check found no warnings.

i Current status:
x This package is not ready to be submitted.

> checks_to_markdown(checks, render = TRUE)


processing file: pkgcheck64c494d2745.Rmd                        (as an
attached file)
.................................................................................................................................

First, this structure is consistent with the README, but not with the
output file from "checks_to_markdown()
- the output (html) from the local machine has no "4. other checks" ...
(see attached file).
- the output (local machine, console) has no check "Function names are
duplicated in other packages" (also not mentioned in README)
- collateral: checks_to_markdown(.., render = TRUE) renders html, but also
(each and every line) on (my) the console.
   ( I don't know if this is an open ISSUE)

Second, the local output (console and html) throws an error for "CI check"
(see above), but on GITHUB (bot) the test passes ..
On GITHUB (bot) appear a test for "Function names ... " (failed) which does
not appear for the local check (console and html)

All this is somehow confusing ..
Well, in my particular case I suppose that I have to change/rename all my
function names? (and examples, documentation ... )
Something like this  .... concstats_hhi, concstats_gini, ...?

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
17/06/22,
20:28:26

**Comment by mpadge** [comment]
@schneiderpy I'm not really sure what your questions are in the above? Please note that GitHub issues respect all markdown formatting, so you should please use that. In other words, please run `checks_to_markdown()`, and paste the markdown-formatted result directly in any issue comments.

The inconsistencies between standardised checks via `pkgcheck-action` and your local checks could be due to any number of things. If you're not seeing local CI checks, that likely suggests that you don't have your GitHub authorization token set up properly. That's explained on [the `pkgcheck` README](https://github.com/ropensci-review-tools/pkgcheck#setup).

The inconsistences between what you see directly on your console screen and the markdown-formatted versions are an unavoidably consequence of compromises necessary in trying to convey a lot of information in compact ways. The most complete version is always the markdown/html version generated by `checks_to_markdown()`, while the screen version will generally be only an abbreviated version of that.

Finally, regarding function names, I would suggest  in your case that yes, you ought to rename a lot of them as many of the names are quite generic. A standard package-specific prefix is the generally recommended approach. This is often some abbreviated form of a full package name, although in your case the function names are generally quite short, so yes, prefixing with `concstats_` would seem like a reasonable approach. Note also https://github.com/ropensci-review-tools/pkgcheck/issues/144 - once that's been implemented these namespace conflicts won't necessarily be an outright fail, but again in the case of your package i would suspect that  reviewers would likely suggest what I'm suggesting here regardless.

**Comment by schneiderpy** [comment]
Thank you for your prompt reply. I thought you were on vacation ...
Actually these are not questions .. it's more like an observation. But I'll
come to this later, if I'll still encounter these issues (using Github
issues?)
(e.g. just look at the readme file of the pkgcheck() package, section:
"what is checked" ... unique_fs_names is not listed, and so in the
summary() which appear on the console screen .... but appears in the html
version ..)

However, I have another question: I have almost changed all functions
(consistently prefixed all with concstats_xxx) ..
Am I right that I have to do a new CRAN / Zenodo submission? (prob. with a
new version number) .. at least that sounds somehow logical to me

Regards,
Andreas


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/07/22,
20:07:04

**Comment by mpadge** [comment]
> Am I right that I have to do a new CRAN / Zenodo submission?

That's entirely up to you, and not related either to this issue, nor to `pkgcheck-action` in general, so I'm going to close this for now. Your questions seem to be more ones of general package development workflow, for which there are several good references. In particular, for potential submissions to rOpenSci, please refer to [our general package development guide](https://devguide.ropensci.org/authors-guide.html), as well as our [statistical software guide](https://stats-devguide.ropensci.org/pkgdev.html).
