### ISSUE TITLE
Add pkgcheck-action envvar to action.yaml

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/pkgcheck-action#37]
@assignUser I use lots of envvars to control tests, and rely a lot on this:
```
identical (Sys.getenv ("GITHUB_WORKFLOW"), "test-coverage"))
```
The problem then arises that this is `FALSE` on pkgcheck-action when I'd like it to be `TRUE`. Obviously we should not mess with that sysvar here (and likely couldn't anyway, I'd guess). It would be useful for me at least for us to use a custom envvar here which I can then query in my own test environments to control whether or not tests are run in this action. I'm going to take the liberty of assigning this to you - thanks!

**Comment by mpadge** [comment]
Oh, actually, I could also just use `GITHUB_WORKFLOW = "pkgcheck"`, so i guess this is not needed? Feel free to close both the PR and this issue in that case, unless you think this could actually help?

**Comment by assignUser** [comment]
I'd be fine with adding an envvar. You trigger tests (as in unit tests not pkgcheck checks) based on that envvar? Where do you want to run them and where don't you want to run them (pkcheck repo only or just not on local installs of users...?)

**Comment by mpadge** [comment]
Nah, I reckon it's all fine without the envvar. The `GITHUB_WORKFLOW` envvar can be used to do everything a custom envvar would do anyway, so i'll just close. Thanks anyway
