### ISSUE TITLE
BUG?: Trouble with `renv`

### ISSUE THREAD

**Issue by HaoZeke** [ropensci-review-tools/pkgcheck-action#40]
I have a package setup with `renv`. On the CI it consistently fails the `pkgcheck` action ([logs](https://github.com/HaoZeke/fastMatMR/actions/runs/6030107784/job/16361208163)). I can see that there's been some discussion on `renv` over in the `pkgcheck` repository but it seems it should have been fixed there?
https://github.com/ropensci-review-tools/pkgcheck/issues/149

I can workaround this by deleting `.Rprofile` but I believe it should work as long as `.Rprofile` doesn't activate `renv` by default..

**Comment by mpadge** [comment]
You're right, it should work as long as renv has been deactivated. If that is the case, and it still fails, can you please share a link to the failing workflow? Thanks

**Comment by mpadge** [comment]
(You already shared the logs, so ignore that)
