### ISSUE TITLE
Issue with R update to 4.4

### ISSUE THREAD

**Issue by abigailkeller** [ropensci-review-tools/pkgcheck-action#45]
My R package was passing the pkgcheck action before the recent R update to 4.4 and now no longer passes (see [github action here](https://github.com/abigailkeller/eDNAjoint/actions/runs/8825592754) with the pass, and [github action here](https://github.com/abigailkeller/eDNAjoint/actions/runs/8870905044) a few days after the update where it no longer passes).

The pkgcheck action fails within 2 minutes with the following error:

` Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * local::.: Can't install dependency ggplot2
  * ggplot2: Can't install dependency MASS
  * MASS: Needs R >= 4.4.0
  * MASS: Needs R >= 4.5
  ---
  Backtrace:
  1. pak::lockfile_create("local::.", lockfile = ".pkgcheck/pkg.lock", …
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
  1. base::withCallingHandlers(cli_message = function(msg) { …
  2. get("lockfile_create_internal", asNamespace("pak"))(...)
  3. prop$stop_for_solution_error()
  4. private$plan$stop_for_solve_error()
  5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
  6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
  7. | base::signalCondition(cond)
  8. global (function (e) …
  Execution halted
  Ran 1/1 deferred expressions`

The error is coming from a dependency issue with MASS (which requires R 4.5?). Is there a way to edit [my yaml file](https://github.com/abigailkeller/eDNAjoint/blob/master/.github/workflows/pkgcheck.yaml) to solve this issue? This file was taken from an [ROpenSci blog post](https://ropensci.org/blog/2022/02/01/pkgcheck-action/).

**Comment by abigailkeller** [comment]
@assignUser Gotcha, thanks for your quick response and those resources! I'm still getting the same error with the following yaml, so I might just wait until Github catches up on R4.4. Thanks!

`name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  # Run on every push to main
  push:
    branches:
      - main
      - master

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: r-lib/actions/setup-r@v2
      - shell: Rscript {0}
        run: |
          if (!requireNamespace("MASS", quietly = TRUE))
            install.packages("MASS")
          library(MASS)
      - uses: ropensci-review-tools/pkgcheck-action@main`

**Comment by mpadge** [comment]
@assignUser I think latest R on GH runners will remain 4.3 until their own [listed versions like here] (https://github.com/actions/runner-images/blob/main/images%2Fubuntu%2FUbuntu2204-Readme.md) are updated. So install-r still resolves to 4.3 and causes probs (although i haven't confirmed that)

**Comment by assignUser** [comment]
Oh yeah, I meant that in general not for this specific issue. Sorry for the confusion.

**Comment by assignUser** [comment]
@abigailkeller The issue is that our docker containers are not being rebuild due to {goodpractice} having been archived, sorry for the inconvenience.

**Comment by abigailkeller** [comment]
@assignUser No worries! I'm nearly ready to submit my package to ROpenSci's statistical software review, and I'm wondering if I should wait until this issue is resolved before submitting? I'm not in a particular rush.

**Comment by assignUser** [comment]
@abigailkeller This should now be resolved! Please let us know if it's still not working!
